services:
  web:
    image: nginx:latest
    ports:
      - '9090:80'
    volumes:
      - ./html:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./html:/var/www/html